use_frameworks!

target 'myPod_Example' do
  pod 'myPod', :path => '../'

  target 'myPod_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
